from . import school
from . import student
from . import teacher
from . import parent
from . import res_users
from . import academic_month
from . import academic_year
from . import grade_line
from . import mother_toungue
from . import school_information
from . import school_standard
from . import student_award
from . import student_cast
from . import student_document
from . import student_family_contact
from . import student_news
from . import student_previous_school
from . import student_reminder
from . import subject_subject
from . import subject_syllabus
from . import document_type
from . import standard_division
from . import standard_standard
